[terminal.shell]
program = "wsl"

[selection]
save_to_clipboard = true

[mouse]
bindings = [
    {mouse="Middle", action="Paste"}
]

[font]
size = 13

  [font.normal]
  family = "Inconsolata-g for Powerline"

[colors.primary]
background = "#1C1C1C"

[debug]
print_events = false
